/* Registro dei 49 indicatori ESG proposti nella tesi (Appendice A, Tabella A.1) e requisiti del modulo Basic del VSME.
 * Metadati metodologici: formula, unità, fonte, classe informativa (A calcolabile · B da acquisire/consolidare · C nuova rilevazione). */
export const PILLARS = {"E": "Ambiente", "S": "Sociale", "C": "Economia", "G": "Governance"};
export const CLASSES = {"A": {"label": "Calcolabile", "text": "Valore presente nelle fonti o calcolabile dagli input disponibili"}, "B": {"label": "Da acquisire o consolidare", "text": "Fonte individuata: il valore va acquisito, aggregato o riconciliato"}, "C": {"label": "Nuova rilevazione", "text": "Richiede nuove rilevazioni, procedure o strumenti"}};
export const ESG_REGISTRY = [
{
"code": "E1",
"pillar": "E",
"name": "Elettricità prelevata da rete",
"formula": "Prelievo rete del periodo",
"unit": "kWh/anno",
"source": "Contatore e fatture",
"cls": "B",
"freq": "Mensile",
"vsme": "B3",
"declared": false
},
{
"code": "E2",
"pillar": "E",
"name": "Energia FV autoconsumata",
"formula": "Letture inverter/contatori, distinguendo l’autoconsumo",
"unit": "kWh/anno",
"source": "Inverter e contatori",
"cls": "B",
"freq": "Mensile",
"vsme": "B3",
"declared": false
},
{
"code": "E3",
"pillar": "E",
"name": "Copertura elettrica da FV",
"formula": "FV autoconsumata / consumo elettrico totale × 100",
"unit": "%",
"source": "E2 + consumo elettrico totale",
"cls": "B",
"freq": "Annuale",
"vsme": "B3",
"declared": false
},
{
"code": "E4",
"pillar": "E",
"name": "Intensità elettrica di stabilimento",
"formula": "Consumo elettrico totale / produzione",
"unit": "kWh/t",
"source": "Dati aziendali",
"cls": "A",
"freq": "Annuale",
"vsme": "B3",
"declared": false
},
{
"code": "E5",
"pillar": "E",
"name": "Consumo di GPL",
"formula": "Consumo misurato o acquisti + scorta iniziale − scorta finale ± rettifiche",
"unit": "kg/anno",
"source": "Dato aziendale; fatture e giacenze",
"cls": "A",
"freq": "Trimestrale",
"vsme": "B3",
"declared": false
},
{
"code": "E6",
"pillar": "E",
"name": "CO₂ da combustione GPL",
"formula": "Quantitativo GPL × fattore emissivo adottato",
"unit": "t CO₂/anno",
"source": "GPL comunicato + fattore emissivo",
"cls": "A",
"freq": "Annuale",
"vsme": "B3",
"declared": false
},
{
"code": "E7",
"pillar": "E",
"name": "CO₂ da elettricità acquistata",
"formula": "kWh rete × FE elettrico / 1.000",
"unit": "kg CO₂/anno",
"source": "ISPRA + E1",
"cls": "B",
"freq": "Annuale",
"vsme": "B3",
"declared": false
},
{
"code": "E8",
"pillar": "E",
"name": "Impronta climatica di prodotto",
"formula": "Studio LCA con inventario e confini definiti",
"unit": "kg CO₂e/t",
"source": "Studio LCA dedicato",
"cls": "C",
"freq": "Triennale",
"vsme": "",
"declared": false
},
{
"code": "E9",
"pillar": "E",
"name": "Prelievo idrico",
"formula": "Somma letture/fatture del periodo",
"unit": "m³/anno",
"source": "Fatture e letture gestore",
"cls": "B",
"freq": "Annuale",
"vsme": "B6",
"declared": false
},
{
"code": "E10",
"pillar": "E",
"name": "Rifiuti prodotti per codice EER",
"formula": "Somma masse per codice EER",
"unit": "kg/anno",
"source": "Registro rifiuti e MUD",
"cls": "B",
"freq": "Annuale",
"vsme": "B7",
"declared": false
},
{
"code": "E11",
"pillar": "E",
"name": "Rifiuti avviati a recupero",
"formula": "Massa a recupero / massa totale rifiuti × 100",
"unit": "%",
"source": "Registro rifiuti / MUD",
"cls": "B",
"freq": "Annuale",
"vsme": "B7",
"declared": false
},
{
"code": "E12",
"pillar": "E",
"name": "Co-prodotti sul totale ingredienti",
"formula": "Massa co-prodotti / massa totale ingredienti × 100",
"unit": "% massa",
"source": "Consumi ingredienti e giacenze",
"cls": "B",
"freq": "Annuale",
"vsme": "B7",
"declared": false
},
{
"code": "E13",
"pillar": "E",
"name": "Approvvigionamento su mare e rotaia",
"formula": "t mare+rotaia / t totali × 100, oppure tkm",
"unit": "%",
"source": "Documenti di trasporto",
"cls": "B",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "E14",
"pillar": "E",
"name": "Materie prime da fornitori certificati",
"formula": "Acquisti da fornitori certificati / acquisti totali × 100",
"unit": "%",
"source": "Questionario ESG / qualifica fornitori",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "E15",
"pillar": "E",
"name": "Soia certificata deforestation-free",
"formula": "Soia certificata / soia totale × 100",
"unit": "%",
"source": "Questionario ESG Q46",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "E16",
"pillar": "E",
"name": "Concentrazione di polveri alle emissioni",
"formula": "Valore da rapporto di autocontrollo",
"unit": "mg/Nm³",
"source": "Rapporti di autocontrollo",
"cls": "B",
"freq": "Secondo AIA",
"vsme": "B4",
"declared": false
},
{
"code": "S1",
"pillar": "S",
"name": "Organico per categoria contrattuale",
"formula": "Conteggio addetti per categoria",
"unit": "n.",
"source": "Questionario / profilo aziendale",
"cls": "A",
"freq": "Annuale",
"vsme": "B8",
"declared": false
},
{
"code": "S2",
"pillar": "S",
"name": "Indice di frequenza degli infortuni",
"formula": "N. infortuni × fattore / ore lavorate",
"unit": "indice",
"source": "Questionario ESG / registrazioni",
"cls": "B",
"freq": "Annuale",
"vsme": "B9",
"declared": true
},
{
"code": "S3",
"pillar": "S",
"name": "Indice di gravità degli infortuni",
"formula": "Giornate perse × fattore / ore lavorate",
"unit": "indice",
"source": "Questionario ESG",
"cls": "A",
"freq": "Annuale",
"vsme": "B9",
"declared": true
},
{
"code": "S4",
"pillar": "S",
"name": "Ore di formazione per dipendente",
"formula": "Ore formazione / addetti inclusi",
"unit": "h/addetto·anno",
"source": "Questionario ESG Q27 / registri formativi",
"cls": "B",
"freq": "Annuale",
"vsme": "B10",
"declared": true
},
{
"code": "S5",
"pillar": "S",
"name": "Divario retributivo di genere",
"formula": "(Retribuzione media uomini − donne) / uomini × 100",
"unit": "%",
"source": "Questionario ESG",
"cls": "A",
"freq": "Annuale",
"vsme": "B10",
"declared": true
},
{
"code": "S6",
"pillar": "S",
"name": "Turnover del personale",
"formula": "Uscite / organico medio × 100",
"unit": "%",
"source": "Questionario ESG",
"cls": "A",
"freq": "Annuale",
"vsme": "B8",
"declared": true
},
{
"code": "S7",
"pillar": "S",
"name": "Donne in ruoli di responsabilità",
"formula": "Donne nei ruoli / totale ruoli × 100",
"unit": "%",
"source": "Questionario ESG / organigramma",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "S8",
"pillar": "S",
"name": "Controlli analitici effettuati",
"formula": "Conteggio analisi nel periodo",
"unit": "n./anno",
"source": "Relazione tecnica / piano controlli",
"cls": "B",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "S9",
"pillar": "S",
"name": "Non conformità di prodotto",
"formula": "Conteggio secondo criterio definito",
"unit": "n./anno",
"source": "Sistema qualità",
"cls": "C",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "S10",
"pillar": "S",
"name": "Reclami ricevuti",
"formula": "Conteggio reclami registrati",
"unit": "n./anno",
"source": "Sistema qualità",
"cls": "C",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "S11",
"pillar": "S",
"name": "Allevatori assistiti dal servizio tecnico",
"formula": "Conteggio soggetti univoci assistiti",
"unit": "n.",
"source": "Rapporti di visita AVIGAL",
"cls": "C",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C1",
"pillar": "C",
"name": "Ricavi delle vendite",
"formula": "Voce A1 del conto economico",
"unit": "€",
"source": "Bilancio 2025",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C2",
"pillar": "C",
"name": "Valore della produzione",
"formula": "Totale sezione A del conto economico",
"unit": "€",
"source": "Bilancio 2025",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C3",
"pillar": "C",
"name": "Incidenza dei costi per materie prime",
"formula": "Costi materie prime / valore produzione × 100",
"unit": "%",
"source": "Bilancio 2025",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C4",
"pillar": "C",
"name": "Incidenza del costo del personale",
"formula": "Costo personale / valore produzione × 100",
"unit": "%",
"source": "Bilancio 2025",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C5",
"pillar": "C",
"name": "Margine netto sui ricavi",
"formula": "Utile / ricavi × 100",
"unit": "%",
"source": "Bilancio 2025",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C6",
"pillar": "C",
"name": "Investimenti in immobilizzazioni materiali",
"formula": "Valore da bilancio / nota integrativa",
"unit": "€",
"source": "Bilancio 2025",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C7",
"pillar": "C",
"name": "Rapporto di capitalizzazione",
"formula": "Patrimonio netto / totale attivo × 100",
"unit": "%",
"source": "Bilancio 2025",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C8",
"pillar": "C",
"name": "Ricavi per addetto",
"formula": "Ricavi / addetti",
"unit": "€/addetto",
"source": "Bilancio + organico",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C9",
"pillar": "C",
"name": "Valore economico generato e distribuito",
"formula": "Riclassificazione del conto economico",
"unit": "€",
"source": "Bilancio 2025",
"cls": "B",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "C10",
"pillar": "C",
"name": "Acquisti da fornitori nazionali",
"formula": "Acquisti Italia / acquisti totali × 100",
"unit": "%",
"source": "Questionario ESG Q51 / contabilità fornitori",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G1",
"pillar": "G",
"name": "Composizione dell’organo amministrativo",
"formula": "Conteggio e quote per categorie definite",
"unit": "n.; %",
"source": "Visura / statuto / questionario",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "G2",
"pillar": "G",
"name": "Adozione del Modello 231",
"formula": "Sì/No",
"unit": "sì/no",
"source": "Questionario Q35 / documentazione societaria",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G3",
"pillar": "G",
"name": "Procedura anticorruzione formalizzata",
"formula": "Sì/No",
"unit": "sì/no",
"source": "Questionario Q36",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G4",
"pillar": "G",
"name": "Episodi di corruzione segnalati",
"formula": "Conteggio episodi nel periodo",
"unit": "n.",
"source": "Questionario Q37",
"cls": "A",
"freq": "Annuale",
"vsme": "B11",
"declared": true
},
{
"code": "G5",
"pillar": "G",
"name": "Certificazioni possedute e validità",
"formula": "Verifica elenco certificati",
"unit": "elenco",
"source": "Certificati acquisiti",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": false
},
{
"code": "G6",
"pillar": "G",
"name": "Audit presso i fornitori",
"formula": "Conteggio audit chiusi",
"unit": "n./anno",
"source": "Questionario Q57",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G7",
"pillar": "G",
"name": "Non conformità presso i fornitori",
"formula": "Conteggio non conformità ESG",
"unit": "n./anno",
"source": "Questionario Q58",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G8",
"pillar": "G",
"name": "Dipendenti formati su etica e compliance",
"formula": "Dipendenti formati / dipendenti inclusi × 100",
"unit": "%",
"source": "Registri formativi",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G9",
"pillar": "G",
"name": "Adozione del Codice Etico",
"formula": "Sì/No",
"unit": "sì/no",
"source": "Questionario ESG",
"cls": "C",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G10",
"pillar": "G",
"name": "Codice di condotta fornitori",
"formula": "Sì/No",
"unit": "sì/no",
"source": "Questionario Q60",
"cls": "C",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G11",
"pillar": "G",
"name": "Fornitori sottoposti a valutazione ESG",
"formula": "Fornitori valutati / fornitori totali × 100",
"unit": "%",
"source": "Qualifica fornitori / Q55",
"cls": "A",
"freq": "Annuale",
"vsme": "",
"declared": true
},
{
"code": "G12",
"pillar": "G",
"name": "Mandato formale di sostenibilità",
"formula": "Sì/No",
"unit": "sì/no",
"source": "Questionario / organigramma",
"cls": "C",
"freq": "Annuale",
"vsme": "",
"declared": true
}
];
export const VSME_BASIC = [
{
"id": "B1",
"name": "Criteri di redazione",
"text": "Base di preparazione, perimetro e informazioni generali sull’impresa",
"kind": "narr"
},
{
"id": "B2",
"name": "Pratiche e iniziative per la transizione",
"text": "Pratiche, politiche e iniziative future per un’economia più sostenibile",
"kind": "narr"
},
{
"id": "B3",
"name": "Energia ed emissioni di gas serra",
"text": "Consumi energetici, Scope 1, Scope 2 location-based, intensità GHG sui ricavi",
"kind": "kpi"
},
{
"id": "B4",
"name": "Inquinamento di aria, acqua e suolo",
"text": "Emissioni inquinanti rilevanti",
"kind": "kpi"
},
{
"id": "B5",
"name": "Biodiversità",
"text": "Siti in o vicino ad aree sensibili; uso del suolo",
"kind": "kpi"
},
{
"id": "B6",
"name": "Acqua",
"text": "Prelievo idrico totale",
"kind": "kpi"
},
{
"id": "B7",
"name": "Risorse, economia circolare e rifiuti",
"text": "Rifiuti prodotti e avviati a recupero; flussi di materiali",
"kind": "kpi"
},
{
"id": "B8",
"name": "Forza lavoro · caratteristiche",
"text": "Dipendenti per contratto e genere; turnover",
"kind": "kpi"
},
{
"id": "B9",
"name": "Forza lavoro · salute e sicurezza",
"text": "Infortuni registrabili, tasso e decessi",
"kind": "kpi"
},
{
"id": "B10",
"name": "Forza lavoro · retribuzione e formazione",
"text": "Salario minimo, divario retributivo, contrattazione, ore di formazione",
"kind": "kpi"
},
{
"id": "B11",
"name": "Condanne e sanzioni per corruzione",
"text": "Numero di condanne e importo delle sanzioni",
"kind": "kpi",
"partial": true
}
];
